### PR TITLE
Pull Upstream

### PR DESCRIPTION
**Pull request by pratikmallya**

### CODE REVIEW

**Comment by pratikmallya** [comment]
🚀

**Comment by pratikmallya** [comment]
PTAL @MHBauer

**Review by MHBauer — DISMISSED** [review]
assuming it results in the same commits and not a merge commit. yay.

**Review by MHBauer — DISMISSED** [review]
Same opinion.

As long as we don't get a merge when it updates, we're fine. (we can probably figure out a way to force push to get matching branches)

**Comment by pratikmallya** [comment]
> assuming it results in the same commits and not a merge commit. yay.

@MHBauer hmm, I'm almost certain its going to result in a merge commit. Is there a way to pull upstream commits without merge commits?

**Comment by MHBauer** [comment]
I've been directly pulling and pushing to the main branches.
`pull upstream-remote` then `push lyft-remote`
If it's a protected branch we may need to modify some permissions to allow that, especially if we end up with merge commits we need to remove. 
my concern is ease of future applications of upstream commits. It is much easier if all of the commits+hashes match.

**Comment by pratikmallya** [comment]
OK yeah that makes sense, let me try that withe the approved commits.

It would be nice if we had some sort of automation to do this e.g. a standalone jenkins job (or equivalent) that we can trigger, which does this push. But since this is a public fork, I'm guessing its not possible?

**Comment by pratikmallya** [comment]
>  You can't commit to this branch because it is protected. 

Welp

**Comment by pratikmallya** [comment]
Let me see if I can change that

**Pull request closed without merging**
